### ISSUE TITLE
why AP values the same when noise levels are different?

### ISSUE THREAD

**Issue by IndigoChildren** [yifanlu0227/CoAlign#13]

**Comment by IndigoChildren** [comment]
So glad you justify the wrong of eval_utils in opencood, and the work you did in appending the use of datasets is really great. But I find something wrong when I run the baseline methods in Coalign, I get the same AP values when noise levels are different. I can figure out why the results come out. btw, in order to align the results I did in opencood, I did not use the global eavl_utils.
![image](https://github.com/yifanlu0227/CoAlign/assets/120171231/a1591d2e-9351-42af-bdee-66501b994ac6)

**Comment by yifanlu0227** [comment]
Did you use tools/inference_w_noise.py？发自我的手机-------- 原始邮件 --------发件人： IndigoChildren ***@***.***>日期： 2023年8月23日周三 22:11收件人： yifanlu0227/CoAlign ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [yifanlu0227/CoAlign] why AP values the same when noise levels are different? (Issue #13)
So glad you justify the wrong of eval_utils in opencood, and the work you did in appending the use of datasets is really great. But I find something wrong when I run the baseline methods in Coalign, I get the same AP values when noise levels are different. I can figure out why the results come out. btw, in order to align the results I did in opencood, I did not use the global eavl_utils.

**Comment by yifanlu0227** [comment]
Please attach the config yaml for cobevt. Other more information would be helpful to solving this problem.

**Comment by yifanlu0227** [comment]
And there is an important difference between coalign and OpenCOOD. In coalign, we all assume that the communication happens once. 

The original OpenCOOD First communicate the agent pose and then transform the point cloud into ego's coordinate. And then encode the feature map for the second communication.

We believe it is an impractical setting. In
 Coalign, feature map are encoded in each agents coordinates, and then the ego agent receive all feature maps and warp them into its coordinate. 

You can first try to figure it out from this perspective.

**Comment by IndigoChildren** [comment]
thanks for your reply, i have find my fault
