### ISSUE TITLE
I also encountered a similar problem, and the error was

### ISSUE THREAD

**Issue by HuangZhe885** [yifanlu0227/CoAlign#20]
I also encountered a similar problem, and the error was 
<img width="1438" alt="image" src="https://github.com/yifanlu0227/CoAlign/assets/44192081/059e797b-bd4d-4e8b-a80f-5f1d15e58aa8">

So I deleted the ’_backup‘ in ’label_world_backup‘ and it ran successfully, but I don’t know if this is correct.

        data[0]['params']['vehicles_front'] = read_json(os.path.join(self.root_dir,frame_info['cooperative_label_path'].replace("label_world", "label_world_backup")))

_Originally posted by @HuangZhe885 in https://github.com/yifanlu0227/CoAlign/issues/11#issuecomment-1770081400_

**Comment by yifanlu0227** [comment]
Sorry for that! I realize I omit an important step in [this instruction](https://siheng-chen.github.io/dataset/dair-v2x-c-complemented/):

**You should rename the folder of original labels with a "_backup" suffix.**

Original labels from THU-AIR will be used for camera-based detection, since the it labels objects within the front view (also camera view). 
Thanks for outing it out. I will update the website soon. Sorry again for themistake.
