### ISSUE TITLE
Confusion about DAIR-V2X metirc 

### ISSUE THREAD

**Issue by jjrCN** [yifanlu0227/CoAlign#4]
First of all thank you for contributing such valuable work. 
Regarding CoAlign's Ap@0.5 on DAIR-V2X, we found that v3 on arXiv has a significant increase compared to v2. The Ap rose from 0.598 (v2) to 0.746 (v3) under the level of no noise, and even other methods such as V2X-ViT also increased from 0.571 (v2) to 0.704 (v3). It's not clear which version is reasonable and correct. In addition, we refer to your previous article Where2Comm, the V2X-ViT in it is 0.543, which is similar to the v2 version.

V2 of CoAlign:
<img width="1128" alt="截屏2023-05-26 下午3 20 05" src="https://github.com/yifanlu0227/CoAlign/assets/37108754/aca39bb6-186b-41f4-bf78-da11437af33e">

V3 of CoAlign:
<img width="1071" alt="截屏2023-05-26 下午3 20 15" src="https://github.com/yifanlu0227/CoAlign/assets/37108754/2cfee1e8-6352-4860-91db-cb8c9ac5fd7e">

**Comment by yifanlu0227** [comment]
Hi! This is because we previous evaluate the AP by OpenCOOD's [eval utils](https://github.com/DerrickXuNu/OpenCOOD/blob/main/opencood/utils/eval_utils.py). But then we find that repo do not sort the detections by scores. We fix this problem in the camera ready version, which is v3 in arxiv. 

You can compare the eval_utils.py, and find the difference.
