### ISSUE TITLE
Can the source code support the CoPercption UAVS dataset?

### ISSUE THREAD

**Issue by WangzcBruce** [yifanlu0227/CoAlign#7]
The CoPercption UAVS dataset is a little hard to deal with.

**Comment by yifanlu0227** [comment]
Hi, currently the codebase does not support the UAVs dataset, and there is no plans to incorporate this dataset in the short future. 

However, to meet your demands, you may consider 2 approaches.

1. The [fusion methods](https://github.com/yifanlu0227/CoAlign/blob/main/opencood/models/fuse_modules/fusion_in_one.py) can be adapted to other codebase since it is nicely organized. Once you have the feature map (warped to BEV view and encoded by some networks), pairwise transformation matrix, you can get the fused features. 

2. Write an basedataset.py for UAVs in this codebase, just like OPV2V, V2XSim 2.0 and DAIR-V2X do. This may involve more changes, such as reading and organizing camera data. And PointPillars is no longer applicable because it is for LiDAR data encoding, you probably need to write another image encoder yourself.

Hope this helps.
