### ISSUE TITLE
problems about running PointPillars with DAIR-V2X

### ISSUE THREAD

**Issue by cp3cp** [yifanlu0227/CoAlign#8]
Hi, thank you for your work. I am trying to evaluate CoAlign on DAIR-V2X with PointPillars as backbone. But there is only example of SECOND on openv2v. So I try to change the configs in *.yaml but it seems that something went wrong about the **data_loader**. Could you provide an example of Evaluation of PointPillars on DAIR-V2X or do you know how to fix this? Thanks in advance.
```
python opencood/tools/pose_graph_pre_calc.py -y opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/precalc.yaml
Noise Added: 0/0/0/0.
Dataset Building
Traceback (most recent call last):
  File "opencood/tools/pose_graph_pre_calc.py", line 187, in <module>
    main()
  File "opencood/tools/pose_graph_pre_calc.py", line 145, in main
    for i, batch_data in enumerate(eval(f"{split}_loader")):
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/mengh3/myconda/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 53, in fetch
    return self.collate_fn(data)
  File "/data/mengh3/CoAlign/opencood/data_utils/datasets/late_fusion_dataset.py", line 415, in collate_batch_test
    transformation_matrix = cav_content['transformation_matrix']
KeyError: 'transformation_matrix'
```

**Comment by yifanlu0227** [comment]
Hi! 

CoAlign is actually based on PointPillar backbone. SECOND is an option for single detector, while the intermediate fusion is still PointPillars.

I think I need to explain how to run CoAlign. There are 3 sequential steps, which is more complex than baseline methods.

1. **Train a single agent detector with uncertainty estimation.** You can choose [coalign/SECOND_uncertainty.yaml](https://github.com/yifanlu0227/CoAlign/blob/main/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/SECOND_uncertainty.yaml) or [coalign/pointpillar_uncertainty.yaml](https://github.com/yifanlu0227/CoAlign/blob/main/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/pointpillar_uncertainty.yaml). In the newest version of our paper, we use the SECOND detector. Simply run `python opencood/tools/train.py -y xxx_uncertainty.yaml` to train the single detector.

2. **Pre-calculate the single detection results.** The reason for this is that single agent detection is the off-the-shelf design, and the inference result is fixed every time. Calculating the detection results for each vehicle in advance can greatly shorten the training time. [tools/pose_graph_pre_calc.py](https://github.com/yifanlu0227/CoAlign/blob/main/opencood/tools/pose_graph_pre_calc.py) and `coalign/precalc.yaml` are used in this step. Remember to modify the `coalign/precalc.yaml` 's [line 97](https://github.com/yifanlu0227/CoAlign/blob/a047d6c120d051b53719455bc50ecb5dbeed0960/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/precalc.yaml#L97) to your own model path.  Then run `python opencood/tools/pose_graph_pre_calc.py -y opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/precalc.yaml` to generate the pre-calculated results.

**Note that** you can just skip these two steps above, and download the pre-calculated results from my [google drive](https://drive.google.com/drive/folders/1otDzESlepuhRBE4ZgJQfpArnpG1TG8uu?usp=sharing). 

3. **Train the CoAlign intermediate fusion**. I think you have notice there are `coalign/pointpillar_coalign_woba.yaml`and `coalign/pointpillar_coalign.yaml` in the folder. `woba` means without_box_alignment, and the difference between them is whether agent-object pose graph optimization is enabled or not. You can look into them to find the difference in [these lines](https://github.com/yifanlu0227/CoAlign/blob/a047d6c120d051b53719455bc50ecb5dbeed0960/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/pointpillar_coalign.yaml#L35C1-L45).  Note that both of them are PointPillar based.  We train the intermediate fusion model with `coalign/pointpillar_coalign_woba.yaml` because training under pose noises can improve model's robustness. And when inference, please copy-and-paste [these lines](https://github.com/yifanlu0227/CoAlign/blob/a047d6c120d051b53719455bc50ecb5dbeed0960/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/pointpillar_coalign.yaml#L35C1-L45) to config.yaml to enable the agent-object pose graph optimization.

In the installation guidance, I have written the steps to run CoAlign, but in Chinese. You can also refer to that to run our model. The English tutorial will be updated soon, sorry for being late.

**Comment by cp3cp** [comment]
Thank you for your early reply!

Now I am running the second step. But the `precalc.yaml` is based on the config of SECOND. For example in [line 72](https://github.com/yifanlu0227/CoAlign/blob/a047d6c120d051b53719455bc50ecb5dbeed0960/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/precalc.yaml#L72), and I change it to `stage1_model: point_pillar_uncertainty` but it still does not work. 

By the way, can I ignore the third step if I only focus on late fusion with box alignment?

**Comment by yifanlu0227** [comment]
Yes, that's because [subsequent lines](https://github.com/yifanlu0227/CoAlign/blob/a047d6c120d051b53719455bc50ecb5dbeed0960/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/precalc.yaml#L75-L95) are also related to SECOND.  You should replace them with [PointPillars's configuration](https://github.com/yifanlu0227/CoAlign/blob/a047d6c120d051b53719455bc50ecb5dbeed0960/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/pointpillar_uncertainty.yaml#L76-L93) if you want to use PointPillars.

For the late fusion question, the answer is Yes. You can insert the `box_align` [yaml entry](https://github.com/yifanlu0227/CoAlign/blob/a047d6c120d051b53719455bc50ecb5dbeed0960/opencood/hypes_yaml/dairv2x/lidar_only_with_noise/coalign/pointpillar_coalign.yaml#L35-L45) to the config.yaml generated from Step 1, and run `python opencood/tools/inference_w_noise.py --model_dir xxx --fusion_method late` to get late fusion with box alignment.

There is a bug in GT label gathering in the code, where the transformation matrix is still noisy for ground truth lables. I've fixed it and please check latest commit.

**Comment by cp3cp** [comment]
Actually the problem is that there is no key named 'transformation_matrix' in [cav_content](https://github.com/yifanlu0227/CoAlign/blob/527ea6b286784cf969498a6e454bec69ab74e39c/opencood/data_utils/datasets/late_fusion_dataset.py#L414)

**Comment by yifanlu0227** [comment]
```
fusion:
  core_method: 'intermediate'
```
because intermediate fusion dataset loads all cavs at the same time, which can be feed into the detection model together. Late fusion dataset only samples one agent in one frame at training time.

There are two remaining errors in your yaml.

1. feature_stride should be 2. The backbone would downsample the 
2. grid_size should be [504, 200, 1], where 504 = (100.8 - (-100.8)) / 0.4. Actually this can be done automatically, if you use `yaml_parser: load_point_pillar_params_stage1`. See the [code](https://github.com/yifanlu0227/CoAlign/blob/527ea6b286784cf969498a6e454bec69ab74e39c/opencood/hypes_yaml/yaml_utils.py#L252). I specified the wrong yaml_parser before, sorry for that.

**Comment by cp3cp** [comment]
It finally works now! I really appreciate your help!
